### ISSUE TITLE
Separation of concerns

### ISSUE THREAD

**Issue by f-masche** [haensl/js-performance#13]
Separate visualization from test logic, which are mixed up right now.
Architectural proposal: implement observer pattern:
`Reporter <- Events - TestRunner`
The TestRunner should emit at least the following events:
* `start`
* `end`
* `error`
* `profileStart`
* `profileEnd`
* `profileError`
* `snippetStart`
* `snippetEnd`
* `snippetError`

**Comment by haensl** [comment]
Done in v1.5.0
